name: CI

on:
  push:
    branches:
      - experiment/cloud-ci # TODO change this to master only when ready

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: "${{ secrets.DOCKER_ORG }}/osca"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
      - name: Print a string
        run: echo here is a string
